name: YCTI CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Show Files
      run: ls

    - name: Build Message
      run: echo "Building Project"

    - name: Test Message
      run: echo "Testing Project"

    - name: Success
      run: echo "CI Pipeline Completed"
